# This file contains values from Cookiecutter

default_context:
  project_name: "nightshift"
  project_description: " a Python package to vcompute and visualize phase coverage"
  organization: "nightshift"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "nightshift"
  email: "None"
  version: "0.0.1"
  line_length: "88"
  create_example_template: "cli"
